srcDb:
  host: 192.168.xx.xx
  port: 1521
  user: xxx
  password: xxx
  type: oracle
sinkDb:
  host: x.x.x.x
  port: 1521
  user: xxxxx
  password: xxxxx
  type: oracle
outputDir: ./result
# !!!`database` `table` `schema` are case sensitive in `oracle`!!!
tableRule:
  -
      src:
      # pattern to match databases for setting properties
      # !!! database should be a `whole instance(or pdb) name` but not a regex when it comes with an `oracle db` !!!
        database: xxxxx
          # pattern to match tables for setting properties
        table: ^xxxx$
          # `schema` only takes effect on `postgresql` and `oracle` and `sqlserver`
        schema: ^xxxxxx$
      sink:
        # pattern to match databases for setting properties
        # !!! database should be a `whole instance(or pdb) name` but not a regex when it comes with an `oracle db` !!!
        database: orcl
        # pattern to match tables for setting properties
        table: ^xxxx$
        # `schema` only takes effect on `postgresql` and `oracle` and `sqlserver`
        schema: ^xxxxxx$
config:
  -  "'server-id' = '1128'"



