srcDb:
  host: 192.168.15.56
  port: 1521
  user: 'C##jacbomqk0721'
  password: 'bomtest$6880'
  type: oracle
sinkDb:
  host: 192.168.15.53
  port: 3306
  user: root
  password: Jac@xxb202012
  type: mysql
outputDir: ./result
# !!!`database` `table` `schema` are case sensitive in `oracle`!!!
tableRule:
  -
      src:
      # pattern to match databases for setting properties
      # !!! database should be a `whole instance(or pdb) name` but not a regex when it comes with an `oracle db` !!!
        database: orcl #^srm-procurementexecution$
      # pattern to match tables for setting properties
        table: ^UPDATELOG$
      # `schema` only takes effect on `postgresql` and `oracle` and `sqlserver`
        schema: ^C##JACBOMQK0721$
      sink:
        # pattern to match databases for setting properties
        # !!! database should be a `whole instance(or pdb) name` but not a regex when it comes with an `oracle db` !!!
        database: ^srm-procurementexecution$
        # pattern to match tables for setting properties
        table: ^payablelist*$
        # `schema` only takes effect on `postgresql` and `oracle` and `sqlserver`
        schema:
config:
  -  "'server-id' = '1128'"



